### ISSUE TITLE
Demonstrate ServiceX -> coffea -> cabinetry -> pyhf pipeline

### ISSUE THREAD

**Issue by alexander-held** [iris-hep/analysis-grand-challenge#1]
Demonstrate a `ServiceX` -> `coffea` -> `cabinetry` -> `pyhf` pipeline on coffea-casa. This can be done by extending the ATLAS Open Data H>ZZ* example developed in [stormsomething/CoffeaHZZAnalysis](https://github.com/stormsomething/CoffeaHZZAnalysis).

**Target date:** Dec 1, 2021

### Requires
- [X] https://github.com/alexander-held/cabinetry/issues/219
- [x] notebooks need to run on coffea-casa https://github.com/iris-hep/analysis-grand-challenge/pull/4

**Comment by alexander-held** [comment]
This pipeline was successfully demonstrated at the AGC tools workshop on Nov 4: https://indico.cern.ch/event/1076231/contributions/4560405/, running on Open Data coffea-casa. As an optional stretch goal, we can add the execution with Dask as well.

**Comment by gordonwatts** [comment]
Woooo!

**Comment by alexander-held** [comment]
This milestone is done as of November 4 2021 when the required pipeline was [demonstrated at the AGC workshop](https://indico.cern.ch/event/1076231/contributions/4560405/). The notebook showcasing this pipeline is provided [on GitHub](https://github.com/iris-hep/analysis-grand-challenge/blob/5da732b58b093b0f049d67fdd7bd0ba00a3d9b8f/workshops/agctools2021/HZZ_analysis_pipeline/HZZ_analysis_pipeline.ipynb). A recording of the talk is attached to the agenda and [available on YouTube](https://www.youtube.com/watch?v=5Vuiy5zoVPk).

The notebook runs on an open data instance of coffea-casa, receives columnar data from `ServiceX` following a `func_adl` query. The data is processed with `coffea`, resulting in the creation of histograms. Those histograms are assembled into a statistical model using `cabinetry`, which calls `pyhf` for statistical inference. The demonstration includes examples of different types of systematic uncertainties, and also showcases the interoperability of different tools within the ecosystem.
