### ISSUE TITLE
Update CMS ttbar requirements.txt

### ISSUE THREAD

**Issue by alexander-held** [iris-hep/analysis-grand-challenge#105]
ServiceX endpoints running 1.1.4 require an updated set of frontend libraries (`pip install servicex-clients` works for that at the moment).

**Comment by ekauffma** [comment]
Also need the `comm` upgrade, right?

**Comment by alexander-held** [comment]
`comm` is pulled in via older versions of `ipykernel`, but I think with what we currently have

https://github.com/iris-hep/analysis-grand-challenge/blob/fc2cf55edfc5fcd45ddd4f083070e8b201eb7fc4/analyses/cms-open-data-ttbar/requirements.txt#L49

this is not needed. The UNL coffea-casa instance had an older version of that library.

**Comment by alexander-held** [comment]
done in #112
