### ISSUE TITLE
Format AGC outputs for HEPData

### ISSUE THREAD

**Issue by alexander-held** [iris-hep/analysis-grand-challenge#108]
We should think about formatting the AGC outputs (figures, tables, etc.) for HEPData compatibility. For some that will be straightforward (HistFactory workspace in JSON format), some others will probably take an intermediate formatting interface to be done. Could also be a feature for `cabinetry` for example.

**Comment by matthewfeickert** [comment]
This is a great idea! We can probably use https://github.com/HEPData/hepdata_lib for easy verification as well.

**Comment by alexander-held** [comment]
resolved by #215 215
