### ISSUE TITLE
Binning of signal and control region observable plots in cabinetry config file is incorrect

### ISSUE THREAD

**Issue by ekauffma** [iris-hep/analysis-grand-challenge#161]
As pointed out by @eguiraud, the bin labels should be 11 bins from 120 to 550. Only the labels are incorrect at this point, so it should be an easy fix

**Comment by alexander-held** [comment]
note to self: we'll also need to backport this if we go ahead with a v1.1

**Comment by alexander-held** [comment]
#165 will fix this for v1, we'll need to port over the same solution to `main` as well (after the refactoring in #158 is done).

**Comment by alexander-held** [comment]
The documentation is currently wrong too: https://agc.readthedocs.io/en/latest/taskbackground.html#observables-to-calculate should say "11 bins from 110 to 550" (and we should add "GeV").
