### ISSUE TITLE
Port histogram re-binning to `main`

### ISSUE THREAD

**Issue by alexander-held** [iris-hep/analysis-grand-challenge#166]
Port over #165 (and eventually replace by a `cabinetry`-native method) to `main` after #158 is merged.

The lower bin edge shift from `120j` -> `110j` should not only be done in the histogram saving but also in the notebook visualization.

**Comment by eguiraud** [comment]
Pointed out by @andriiknu actually :grimacing: 

According to the spec it should be `>` everywhere: https://agc.readthedocs.io/en/latest/versionsdescription.html

**Comment by alexander-held** [comment]
#174 is dedicated to tracking the b-tagging.

**Comment by alexander-held** [comment]
While doing this (which will trigger the need for new reference histograms), also remove the offsetting by 1e-6 in https://github.com/iris-hep/analysis-grand-challenge/blob/ca067898756ff4bda17237e0e657121539cc40ee/analyses/cms-open-data-ttbar/utils/file_output.py#L8-L9 (this was a workaround to avoid issues due to empty bins for the statistical inference stage).
