### ISSUE TITLE
pyhf + funcX demonstrator

### ISSUE THREAD

**Issue by alexander-held** [iris-hep/analysis-grand-challenge#33]
Deploy pyhf + funcX at SSL / UNL and showcase demonstrator at the next AGC workshop (#29). Workshop attendees should be able to access this service to try out the functionality.

**Target date**: end of April 2022

### Requirements
- [ ] [to be added]

**Comment by matthewfeickert** [comment]
Could we setup a single end point of deployment for users? Can we do this at both the Nebraska coffea-casa and UChicago analysis facility? Or does it make sense to just do one?

**Comment by oshadura** [comment]
@matthewfeickert we will aim to have both on Nebraska coffea-casa and UChicago analysis facility

**Comment by alexander-held** [comment]
@matthewfeickert's repository from vCHEP 2021: https://github.com/matthewfeickert/distributed-inference-with-pyhf-and-funcX
