### ISSUE TITLE
IRIS-HEP / AGC Demo day 16.12.2022

### ISSUE THREAD

**Issue by oshadura** [iris-hep/analysis-grand-challenge#87]
We'll be organizing a demo day on Friday 16.12.2022 at 11am Central, 5pm Central European Time.

Agenda
===========

- Dependency management for complex analysis at coffea-casa facility + JWT generation @oshadura @Andrew42 @Sam6734
- ServiceX: ROOT files from uproot transformer & scaling @ivukotic @fengpinghu @BenGalewsky @talvandaalen @sthapa  
- Data management of HEP data (Apache Iceberg) @JayjeetAtGithub 
- Integrating AGC pipeline at BNL facility @matthewfeickert
- First steps using inference server at coffea-casa facility @ekauffma @alexander-held @clundst @oshadura 
- Using JWT tokens for XCache at coffea-casa facility @jthiltges @oshadura @clundst @Sam6734

Indico agenda
===========
See https://indico.cern.ch/event/1218004/

cc: @bbockelm

**Comment by matthewfeickert** [comment]
I'm excited for this! :) 

If people want to follow along with what I'm doing for testing at BNL in advance:
* [GitHub repo for Analysis Systems image Dockerfile](https://github.com/iris-hep/analysis-systems-base).
* [Ongoing discussion on ATLAS Tier-3 Analysis Facilities Discourse](https://atlas-talk.sdcc.bnl.gov/t/how-to-activate-python-virtual-environments-with-custom-images/269/) on getting things working out of the box on the [BNL SDCC Jupyter test infrastructure](https://atlas-jupyter-test.sdcc.bnl.gov/).

**Comment by alexander-held** [comment]
This demo day is done, recording is attached to the agenda. Next demo day (tomorrow!) is tracked in #95.
