### ISSUE TITLE
IRIS-HEP / AGC Demo day 24.02.2023

### ISSUE THREAD

**Issue by oshadura** [iris-hep/analysis-grand-challenge#95]
Preliminary draft:
- Coffea-casa with working cephfs
- Distributed xcache with  redirector at coffea-casa
- ServiceX working with CMS IAM token
- distributed RDF on coffea-casa
- scaling ServiceX

agenda: https://indico.cern.ch/event/1232470/

**Comment by bbockelm** [comment]
Further ideas from brainstorming (trying to keep items in priority order):

Coffea-Casa:
- Generate token with appropriate write scopes from IAM.
- Dependency manager (demo delayed from December)
- Demonstrate deployment of Coffea-Casa on minikube.

ServiceX:
- ServiceX client uses IAM token to authentication; no separate authorization step from inside Coffea-Casa.  Config file is auto-generated.
- Dashboard available from within JupyterHub.
- More robust uproot transformer (writing out multiple columns, etc).

**Comment by BenGalewsky** [comment]
We should have ServiceX with multiple code generator backends

**Comment by oshadura** [comment]
Multi-user simultanious scale tests at various facilities

**Comment by oshadura** [comment]
Data management with Iceberg: "TTree friend" functionality

**Comment by masonproffitt** [comment]
> * More robust uproot transformer (writing out multiple columns, etc).

I'm a bit confused here; could you explain what this means, @bbockelm? Writing multiple columns is already standard for the Uproot transformer.

**Comment by alexander-held** [comment]
Closing this as the demo day is done. Recordings are attached to the agenda and can be found at https://youtu.be/zb1va9YDqY4. The next demo day will be integrated into the AGC workshop https://indico.cern.ch/e/agc-workshop-2023.

Not sure about the "multiple columns" point, perhaps it refers to the handling of multiple trees in the input dataset instead?
